name: Build and Release

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build-self-contained:
    runs-on: windows-latest
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Restore dependencies
      run: dotnet restore

    - name: Build self-contained
      run: dotnet publish --configuration Release --runtime win-x64 -p:PublishSingleFile=true --self-contained true

    - name: Zip self-contained artifact
      run: |
        $publishDir = Get-ChildItem -Path . -Recurse -Filter publish | Where-Object { $_.FullName -match 'bin\\Release\\.*\\publish$' } \
            Write-Output "Publish directory: $($publishDir.FullName)" \
            Compress-Archive -Path "$($publishDir.FullName)\\*" -DestinationPath self-contained-app.zip
      shell: pwsh

    - name: Upload self-contained artifact
      uses: actions/upload-artifact@v4
      with:
        name: self-contained-app
        path: ./output-self-contained

  build-framework-dependent:
    runs-on: windows-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Restore dependencies
      run: dotnet restore

    - name: Build framework-dependent
      run: dotnet publish --configuration Release
      
      run: |
        $publishDir = Get-ChildItem -Path . -Recurse -Filter publish | Where-Object { $_.FullName -match 'bin\\Release\\.*\\publish$' } \
            Write-Output "Publish directory: $($publishDir.FullName)" \
            Compress-Archive -Path "$($publishDir.FullName)\\*" -DestinationPath framework-dependent-app.zip \
      shell: pwsh

    - name: Upload framework-dependent artifact
      uses: actions/upload-artifact@v4
      with:
        name: framework-dependent-app
        path: ./output-framework-dependent
