name: Build and Release

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  setup-dotnet:
    runs-on: windows-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: '8.x.x'

    - name: Restore dependencies
      run: dotnet restore

    - name: Save dependencies
      uses: actions/upload-artifact@v4
      with:
        name: restored-dependencies
        path: ./

  build-self-contained:
    runs-on: windows-latest
    needs: setup-dotnet

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Download restored dependencies
      uses: actions/download-artifact@v4
      with:
        name: restored-dependencies

    - name: Build self-contained
      run: dotnet publish --configuration Release --self-contained --runtime win-x64 --output ./output-self-contained

    - name: Upload self-contained artifact
      uses: actions/upload-artifact@v4
      with:
        name: self-contained-app
        path: ./output-self-contained

  build-framework-dependent:
    runs-on: windows-latest
    needs: setup-dotnet

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Download restored dependencies
      uses: actions/download-artifact@v4
      with:
        name: restored-dependencies

    - name: Build framework-dependent
      run: dotnet publish --configuration Release --output ./output-framework-dependent

    - name: Upload framework-dependent artifact
      uses: actions/upload-artifact@v4
      with:
        name: framework-dependent-app
        path: ./output-framework-dependent
