name: Build and Release

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build-self-contained:
    runs-on: windows-latest
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Restore dependencies
      run: dotnet restore

    - name: Build self-contained
      run: dotnet publish --configuration Release --runtime win-x64 -p:PublishSingleFile=true --self-contained true

    - name: Upload self-contained artifact
      uses: actions/upload-artifact@v4
      with:
        name: self-contained-app
        path: ./output-self-contained

  build-framework-dependent:
    runs-on: windows-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Restore dependencies
      run: dotnet restore

    - name: Build framework-dependent
      run: dotnet publish --configuration Release

    - name: Upload framework-dependent artifact
      uses: actions/upload-artifact@v4
      with:
        name: framework-dependent-app
        path: ./output-framework-dependent
